### ISSUE TITLE
R aborts when trying to use lsmeans with gls

### ISSUE THREAD

**Issue by jeonifer2** [cran/emmeans#1]
This is the warning I get when try to use lsmeans/emmeans with gls. 
Error in oXy[, p + 1] : subscript out of bounds
In addition: Warning message:
In conLin$Xy * varWeights(object) :
  longer object length is not a multiple of shorter object length
Error in emm_basis.gls(object, trms, xlev, grid, misc = attr(data, "misc"),  : 
  Unable to estimate Satterthwaite parameters

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
